name: "Arch Linux: Build and push toolbx image"

permissions: read-all

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - archlinux/**
      - .github/workflows/archlinux.yaml
  schedule:
    - cron:  '0 0 * * MON'

env:
  distro: 'archlinux'
  distro_pretty: 'Arch Linux'

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-images:
    name: Build and push images

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          platforms: linux/amd64
          context: ${{ env.distro }}/${{ matrix.release }}
          image: ${{ env.distro }}-toolbox
          tags: latest
          containerfiles: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          layers: false
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          image: ${{ env.distro }}-toolbox
          registry: ${{ env.REGISTRY }}
          tags: latest
